# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName("root")
        root.setWindowModality(QtCore.Qt.WindowModal)
        root.setEnabled(True)
        root.resize(766, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(root.sizePolicy().hasHeightForWidth())
        root.setSizePolicy(sizePolicy)
        root.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        root.setFont(font)
        root.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/SerialTool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        root.setWindowIcon(icon)
        root.setIconSize(QtCore.QSize(16, 16))
        root.setAnimated(True)
        root.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(root)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 4, -1, -1)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.DD_baudrate = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DD_baudrate.sizePolicy().hasHeightForWidth())
        self.DD_baudrate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.DD_baudrate.setFont(font)
        self.DD_baudrate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.DD_baudrate.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DD_baudrate.setEditable(True)
        self.DD_baudrate.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.DD_baudrate.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.DD_baudrate.setObjectName("DD_baudrate")
        self.gridLayout.addWidget(self.DD_baudrate, 1, 5, 1, 1)
        self.PB_commPortCtrl = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_commPortCtrl.sizePolicy().hasHeightForWidth())
        self.PB_commPortCtrl.setSizePolicy(sizePolicy)
        self.PB_commPortCtrl.setMinimumSize(QtCore.QSize(0, 0))
        self.PB_commPortCtrl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.PB_commPortCtrl.setFont(font)
        self.PB_commPortCtrl.setObjectName("PB_commPortCtrl")
        self.gridLayout.addWidget(self.PB_commPortCtrl, 1, 7, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 6, 1, 1)
        self.PB_serialSetup = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_serialSetup.setIcon(icon1)
        self.PB_serialSetup.setIconSize(QtCore.QSize(14, 14))
        self.PB_serialSetup.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_serialSetup.setAutoRaise(True)
        self.PB_serialSetup.setObjectName("PB_serialSetup")
        self.gridLayout.addWidget(self.PB_serialSetup, 1, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 1, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 4, 1, 1)
        self.PB_refreshCommPortsList = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_refreshCommPortsList.setIcon(icon2)
        self.PB_refreshCommPortsList.setIconSize(QtCore.QSize(14, 14))
        self.PB_refreshCommPortsList.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_refreshCommPortsList.setAutoRaise(True)
        self.PB_refreshCommPortsList.setObjectName("PB_refreshCommPortsList")
        self.gridLayout.addWidget(self.PB_refreshCommPortsList, 1, 3, 1, 1)
        self.DD_commPortSelector = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DD_commPortSelector.sizePolicy().hasHeightForWidth())
        self.DD_commPortSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.DD_commPortSelector.setFont(font)
        self.DD_commPortSelector.setEditable(False)
        self.DD_commPortSelector.setCurrentText("")
        self.DD_commPortSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.DD_commPortSelector.setObjectName("DD_commPortSelector")
        self.gridLayout.addWidget(self.DD_commPortSelector, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(53, 53, 53);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TI_data2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data2.setFont(font)
        self.TI_data2.setDragEnabled(True)
        self.TI_data2.setClearButtonEnabled(True)
        self.TI_data2.setObjectName("TI_data2")
        self.gridLayout_2.addWidget(self.TI_data2, 1, 1, 1, 1)
        self.TI_data8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data8.setFont(font)
        self.TI_data8.setDragEnabled(True)
        self.TI_data8.setClearButtonEnabled(True)
        self.TI_data8.setObjectName("TI_data8")
        self.gridLayout_2.addWidget(self.TI_data8, 7, 1, 1, 1)
        self.PB_send2 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send2.setObjectName("PB_send2")
        self.gridLayout_2.addWidget(self.PB_send2, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.PB_send5 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send5.setObjectName("PB_send5")
        self.gridLayout_2.addWidget(self.PB_send5, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 7, 0, 1, 1)
        self.PB_send3 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send3.setObjectName("PB_send3")
        self.gridLayout_2.addWidget(self.PB_send3, 2, 3, 1, 1)
        self.TI_data6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data6.setFont(font)
        self.TI_data6.setDragEnabled(True)
        self.TI_data6.setClearButtonEnabled(True)
        self.TI_data6.setObjectName("TI_data6")
        self.gridLayout_2.addWidget(self.TI_data6, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.TI_note6 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note6.setFont(font)
        self.TI_note6.setDragEnabled(True)
        self.TI_note6.setClearButtonEnabled(True)
        self.TI_note6.setObjectName("TI_note6")
        self.gridLayout_2.addWidget(self.TI_note6, 5, 2, 1, 1)
        self.TI_data7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data7.setFont(font)
        self.TI_data7.setDragEnabled(True)
        self.TI_data7.setClearButtonEnabled(True)
        self.TI_data7.setObjectName("TI_data7")
        self.gridLayout_2.addWidget(self.TI_data7, 6, 1, 1, 1)
        self.PB_send6 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send6.setObjectName("PB_send6")
        self.gridLayout_2.addWidget(self.PB_send6, 5, 3, 1, 1)
        self.TI_note8 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note8.setFont(font)
        self.TI_note8.setDragEnabled(True)
        self.TI_note8.setClearButtonEnabled(True)
        self.TI_note8.setObjectName("TI_note8")
        self.gridLayout_2.addWidget(self.TI_note8, 7, 2, 1, 1)
        self.TI_note5 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note5.setFont(font)
        self.TI_note5.setDragEnabled(True)
        self.TI_note5.setClearButtonEnabled(True)
        self.TI_note5.setObjectName("TI_note5")
        self.gridLayout_2.addWidget(self.TI_note5, 4, 2, 1, 1)
        self.TI_note1 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note1.setFont(font)
        self.TI_note1.setDragEnabled(True)
        self.TI_note1.setClearButtonEnabled(True)
        self.TI_note1.setObjectName("TI_note1")
        self.gridLayout_2.addWidget(self.TI_note1, 0, 2, 1, 1)
        self.PB_send4 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send4.setObjectName("PB_send4")
        self.gridLayout_2.addWidget(self.PB_send4, 3, 3, 1, 1)
        self.TI_data1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data1.setFont(font)
        self.TI_data1.setText("")
        self.TI_data1.setDragEnabled(True)
        self.TI_data1.setClearButtonEnabled(True)
        self.TI_data1.setObjectName("TI_data1")
        self.gridLayout_2.addWidget(self.TI_data1, 0, 1, 1, 1)
        self.PB_send7 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send7.setObjectName("PB_send7")
        self.gridLayout_2.addWidget(self.PB_send7, 6, 3, 1, 1)
        self.TI_note2 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note2.setFont(font)
        self.TI_note2.setDragEnabled(True)
        self.TI_note2.setClearButtonEnabled(True)
        self.TI_note2.setObjectName("TI_note2")
        self.gridLayout_2.addWidget(self.TI_note2, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.TI_data5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data5.setFont(font)
        self.TI_data5.setDragEnabled(True)
        self.TI_data5.setClearButtonEnabled(True)
        self.TI_data5.setObjectName("TI_data5")
        self.gridLayout_2.addWidget(self.TI_data5, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.TI_data4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data4.setFont(font)
        self.TI_data4.setDragEnabled(True)
        self.TI_data4.setClearButtonEnabled(True)
        self.TI_data4.setObjectName("TI_data4")
        self.gridLayout_2.addWidget(self.TI_data4, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.TI_note3 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note3.setFont(font)
        self.TI_note3.setDragEnabled(True)
        self.TI_note3.setClearButtonEnabled(True)
        self.TI_note3.setObjectName("TI_note3")
        self.gridLayout_2.addWidget(self.TI_note3, 2, 2, 1, 1)
        self.TI_note7 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note7.setFont(font)
        self.TI_note7.setDragEnabled(True)
        self.TI_note7.setClearButtonEnabled(True)
        self.TI_note7.setObjectName("TI_note7")
        self.gridLayout_2.addWidget(self.TI_note7, 6, 2, 1, 1)
        self.TI_note4 = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TI_note4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TI_note4.setFont(font)
        self.TI_note4.setDragEnabled(True)
        self.TI_note4.setClearButtonEnabled(True)
        self.TI_note4.setObjectName("TI_note4")
        self.gridLayout_2.addWidget(self.TI_note4, 3, 2, 1, 1)
        self.PB_send8 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send8.setObjectName("PB_send8")
        self.gridLayout_2.addWidget(self.PB_send8, 7, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.PB_send1 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_send1.setObjectName("PB_send1")
        self.gridLayout_2.addWidget(self.PB_send1, 0, 3, 1, 1)
        self.TI_data3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TI_data3.setFont(font)
        self.TI_data3.setDragEnabled(True)
        self.TI_data3.setClearButtonEnabled(True)
        self.TI_data3.setObjectName("TI_data3")
        self.gridLayout_2.addWidget(self.TI_data3, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PB_sendSequence2 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_sendSequence2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PB_sendSequence2.setObjectName("PB_sendSequence2")
        self.gridLayout_3.addWidget(self.PB_sendSequence2, 2, 2, 1, 1)
        self.PB_sendSequence3 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_sendSequence3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PB_sendSequence3.setObjectName("PB_sendSequence3")
        self.gridLayout_3.addWidget(self.PB_sendSequence3, 3, 2, 1, 1)
        self.PB_sendSequence1 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_sendSequence1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PB_sendSequence1.setObjectName("PB_sendSequence1")
        self.gridLayout_3.addWidget(self.PB_sendSequence1, 1, 2, 1, 1)
        self.TI_sequence3 = QtWidgets.QLineEdit(self.centralwidget)
        self.TI_sequence3.setInputMask("")
        self.TI_sequence3.setText("")
        self.TI_sequence3.setClearButtonEnabled(True)
        self.TI_sequence3.setObjectName("TI_sequence3")
        self.gridLayout_3.addWidget(self.TI_sequence3, 3, 0, 1, 1)
        self.TI_sequence2 = QtWidgets.QLineEdit(self.centralwidget)
        self.TI_sequence2.setInputMask("")
        self.TI_sequence2.setText("")
        self.TI_sequence2.setClearButtonEnabled(True)
        self.TI_sequence2.setObjectName("TI_sequence2")
        self.gridLayout_3.addWidget(self.TI_sequence2, 2, 0, 1, 1)
        self.TI_sequence1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TI_sequence1.sizePolicy().hasHeightForWidth())
        self.TI_sequence1.setSizePolicy(sizePolicy)
        self.TI_sequence1.setInputMask("")
        self.TI_sequence1.setText("")
        self.TI_sequence1.setClearButtonEnabled(True)
        self.TI_sequence1.setObjectName("TI_sequence1")
        self.gridLayout_3.addWidget(self.TI_sequence1, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(53, 53, 53);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_clearLog = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_clearLog.setIcon(icon3)
        self.PB_clearLog.setIconSize(QtCore.QSize(14, 14))
        self.PB_clearLog.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_clearLog.setAutoRaise(True)
        self.PB_clearLog.setObjectName("PB_clearLog")
        self.horizontalLayout_2.addWidget(self.PB_clearLog)
        self.PB_exportLog = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_exportLog.setIcon(icon4)
        self.PB_exportLog.setIconSize(QtCore.QSize(14, 14))
        self.PB_exportLog.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_exportLog.setAutoRaise(True)
        self.PB_exportLog.setObjectName("PB_exportLog")
        self.horizontalLayout_2.addWidget(self.PB_exportLog)
        self.PB_exportRxTxData = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon-save-raw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_exportRxTxData.setIcon(icon5)
        self.PB_exportRxTxData.setIconSize(QtCore.QSize(14, 14))
        self.PB_exportRxTxData.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_exportRxTxData.setAutoRaise(True)
        self.PB_exportRxTxData.setObjectName("PB_exportRxTxData")
        self.horizontalLayout_2.addWidget(self.PB_exportRxTxData)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.CB_rxToLog = QtWidgets.QCheckBox(self.centralwidget)
        self.CB_rxToLog.setChecked(True)
        self.CB_rxToLog.setObjectName("CB_rxToLog")
        self.horizontalLayout_2.addWidget(self.CB_rxToLog)
        self.CB_txToLog = QtWidgets.QCheckBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(79, 127, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 127, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.CB_txToLog.setPalette(palette)
        self.CB_txToLog.setChecked(True)
        self.CB_txToLog.setObjectName("CB_txToLog")
        self.horizontalLayout_2.addWidget(self.CB_txToLog)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.RB_outputRepresentationString = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_outputRepresentationString.setChecked(True)
        self.RB_outputRepresentationString.setObjectName("RB_outputRepresentationString")
        self.RB_GROUP_outputRepresentation = QtWidgets.QButtonGroup(root)
        self.RB_GROUP_outputRepresentation.setObjectName("RB_GROUP_outputRepresentation")
        self.RB_GROUP_outputRepresentation.addButton(self.RB_outputRepresentationString)
        self.horizontalLayout_2.addWidget(self.RB_outputRepresentationString)
        self.RB_outputRepresentationIntList = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_outputRepresentationIntList.setObjectName("RB_outputRepresentationIntList")
        self.RB_GROUP_outputRepresentation.addButton(self.RB_outputRepresentationIntList)
        self.horizontalLayout_2.addWidget(self.RB_outputRepresentationIntList)
        self.RB_outputRepresentationHexList = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_outputRepresentationHexList.setObjectName("RB_outputRepresentationHexList")
        self.RB_GROUP_outputRepresentation.addButton(self.RB_outputRepresentationHexList)
        self.horizontalLayout_2.addWidget(self.RB_outputRepresentationHexList)
        self.RB_outputRepresentationAsciiList = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_outputRepresentationAsciiList.setObjectName("RB_outputRepresentationAsciiList")
        self.RB_GROUP_outputRepresentation.addButton(self.RB_outputRepresentationAsciiList)
        self.horizontalLayout_2.addWidget(self.RB_outputRepresentationAsciiList)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.CB_rxNewLine = QtWidgets.QCheckBox(self.centralwidget)
        self.CB_rxNewLine.setEnabled(True)
        self.CB_rxNewLine.setChecked(False)
        self.CB_rxNewLine.setObjectName("CB_rxNewLine")
        self.horizontalLayout_2.addWidget(self.CB_rxNewLine)
        self.SB_rxTimeoutMs = QtWidgets.QSpinBox(self.centralwidget)
        self.SB_rxTimeoutMs.setEnabled(False)
        self.SB_rxTimeoutMs.setPrefix("")
        self.SB_rxTimeoutMs.setMinimum(10)
        self.SB_rxTimeoutMs.setMaximum(9990)
        self.SB_rxTimeoutMs.setSingleStep(10)
        self.SB_rxTimeoutMs.setObjectName("SB_rxTimeoutMs")
        self.horizontalLayout_2.addWidget(self.SB_rxTimeoutMs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PB_autoScroll = QtWidgets.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_autoScroll.setIcon(icon6)
        self.PB_autoScroll.setIconSize(QtCore.QSize(14, 14))
        self.PB_autoScroll.setCheckable(True)
        self.PB_autoScroll.setChecked(True)
        self.PB_autoScroll.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PB_autoScroll.setAutoRaise(True)
        self.PB_autoScroll.setArrowType(QtCore.Qt.NoArrow)
        self.PB_autoScroll.setObjectName("PB_autoScroll")
        self.horizontalLayout_2.addWidget(self.PB_autoScroll)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TE_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.TE_log.setAcceptDrops(False)
        self.TE_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TE_log.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.TE_log.setTabStopWidth(20)
        self.TE_log.setCursorWidth(1)
        self.TE_log.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.TE_log.setOpenExternalLinks(True)
        self.TE_log.setObjectName("TE_log")
        self.horizontalLayout.addWidget(self.TE_log)
        self.verticalLayout.addLayout(self.horizontalLayout)
        root.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(root)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.PB_fileMenu_recentlyUsedConfigurations = QtWidgets.QMenu(self.menuFile)
        self.PB_fileMenu_recentlyUsedConfigurations.setObjectName("PB_fileMenu_recentlyUsedConfigurations")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        root.setMenuBar(self.menuBar)
        self.PB_fileMenu_saveConfiguration = QtWidgets.QAction(root)
        self.PB_fileMenu_saveConfiguration.setObjectName("PB_fileMenu_saveConfiguration")
        self.PB_fileMenu_loadConfiguration = QtWidgets.QAction(root)
        self.PB_fileMenu_loadConfiguration.setObjectName("PB_fileMenu_loadConfiguration")
        self.PB_fileMenu_newConfiguration = QtWidgets.QAction(root)
        self.PB_fileMenu_newConfiguration.setObjectName("PB_fileMenu_newConfiguration")
        self.setup_clear_log = QtWidgets.QAction(root)
        self.setup_clear_log.setObjectName("setup_clear_log")
        self.setup_hex_output = QtWidgets.QAction(root)
        self.setup_hex_output.setCheckable(True)
        self.setup_hex_output.setChecked(False)
        self.setup_hex_output.setObjectName("setup_hex_output")
        self.setup_ascii_output = QtWidgets.QAction(root)
        self.setup_ascii_output.setCheckable(True)
        self.setup_ascii_output.setObjectName("setup_ascii_output")
        self.setup_serial = QtWidgets.QAction(root)
        self.setup_serial.setObjectName("setup_serial")
        self.file_about = QtWidgets.QAction(root)
        self.file_about.setObjectName("file_about")
        self.setup_string_output = QtWidgets.QAction(root)
        self.setup_string_output.setCheckable(True)
        self.setup_string_output.setChecked(True)
        self.setup_string_output.setObjectName("setup_string_output")
        self.PB_helpMenu_about = QtWidgets.QAction(root)
        self.PB_helpMenu_about.setObjectName("PB_helpMenu_about")
        self.PB_helpMenu_docs = QtWidgets.QAction(root)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/external-link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_helpMenu_docs.setIcon(icon7)
        self.PB_helpMenu_docs.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.PB_helpMenu_docs.setObjectName("PB_helpMenu_docs")
        self.PB_helpMenu_checkForUpdate = QtWidgets.QAction(root)
        self.PB_helpMenu_checkForUpdate.setEnabled(False)
        self.PB_helpMenu_checkForUpdate.setObjectName("PB_helpMenu_checkForUpdate")
        self.actionAsd = QtWidgets.QAction(root)
        self.actionAsd.setObjectName("actionAsd")
        self.PB_helpMenu_openLogFile = QtWidgets.QAction(root)
        self.PB_helpMenu_openLogFile.setObjectName("PB_helpMenu_openLogFile")
        self.menuFile.addAction(self.PB_fileMenu_newConfiguration)
        self.menuFile.addAction(self.PB_fileMenu_saveConfiguration)
        self.menuFile.addAction(self.PB_fileMenu_loadConfiguration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.PB_fileMenu_recentlyUsedConfigurations.menuAction())
        self.menuHelp.addAction(self.PB_helpMenu_docs)
        self.menuHelp.addAction(self.PB_helpMenu_about)
        self.menuHelp.addAction(self.PB_helpMenu_openLogFile)
        self.menuHelp.addAction(self.PB_helpMenu_checkForUpdate)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)
        root.setTabOrder(self.PB_serialSetup, self.DD_commPortSelector)
        root.setTabOrder(self.DD_commPortSelector, self.PB_refreshCommPortsList)
        root.setTabOrder(self.PB_refreshCommPortsList, self.DD_baudrate)
        root.setTabOrder(self.DD_baudrate, self.PB_commPortCtrl)
        root.setTabOrder(self.PB_commPortCtrl, self.TI_data1)
        root.setTabOrder(self.TI_data1, self.TI_note1)
        root.setTabOrder(self.TI_note1, self.PB_send1)
        root.setTabOrder(self.PB_send1, self.TI_data2)
        root.setTabOrder(self.TI_data2, self.TI_note2)
        root.setTabOrder(self.TI_note2, self.PB_send2)
        root.setTabOrder(self.PB_send2, self.TI_data3)
        root.setTabOrder(self.TI_data3, self.TI_note3)
        root.setTabOrder(self.TI_note3, self.PB_send3)
        root.setTabOrder(self.PB_send3, self.TI_data4)
        root.setTabOrder(self.TI_data4, self.TI_note4)
        root.setTabOrder(self.TI_note4, self.PB_send4)
        root.setTabOrder(self.PB_send4, self.TI_data5)
        root.setTabOrder(self.TI_data5, self.TI_note5)
        root.setTabOrder(self.TI_note5, self.PB_send5)
        root.setTabOrder(self.PB_send5, self.TI_data6)
        root.setTabOrder(self.TI_data6, self.TI_note6)
        root.setTabOrder(self.TI_note6, self.PB_send6)
        root.setTabOrder(self.PB_send6, self.TI_data7)
        root.setTabOrder(self.TI_data7, self.TI_note7)
        root.setTabOrder(self.TI_note7, self.PB_send7)
        root.setTabOrder(self.PB_send7, self.TI_data8)
        root.setTabOrder(self.TI_data8, self.TI_note8)
        root.setTabOrder(self.TI_note8, self.PB_send8)
        root.setTabOrder(self.PB_send8, self.TI_sequence1)
        root.setTabOrder(self.TI_sequence1, self.PB_sendSequence1)
        root.setTabOrder(self.PB_sendSequence1, self.TI_sequence2)
        root.setTabOrder(self.TI_sequence2, self.PB_sendSequence2)
        root.setTabOrder(self.PB_sendSequence2, self.TI_sequence3)
        root.setTabOrder(self.TI_sequence3, self.PB_sendSequence3)
        root.setTabOrder(self.PB_sendSequence3, self.PB_clearLog)
        root.setTabOrder(self.PB_clearLog, self.PB_exportLog)
        root.setTabOrder(self.PB_exportLog, self.PB_exportRxTxData)
        root.setTabOrder(self.PB_exportRxTxData, self.CB_rxToLog)
        root.setTabOrder(self.CB_rxToLog, self.CB_txToLog)
        root.setTabOrder(self.CB_txToLog, self.RB_outputRepresentationString)
        root.setTabOrder(self.RB_outputRepresentationString, self.RB_outputRepresentationIntList)
        root.setTabOrder(self.RB_outputRepresentationIntList, self.RB_outputRepresentationHexList)
        root.setTabOrder(self.RB_outputRepresentationHexList, self.RB_outputRepresentationAsciiList)
        root.setTabOrder(self.RB_outputRepresentationAsciiList, self.PB_autoScroll)
        root.setTabOrder(self.PB_autoScroll, self.TE_log)

    def retranslateUi(self, root):
        _translate = QtCore.QCoreApplication.translate
        root.setWindowTitle(_translate("root", "Serial Tool"))
        self.DD_baudrate.setToolTip(_translate("root", "<html><head/><body><p>Select communication baudrate.</p><p><br/></p></body></html>"))
        self.PB_commPortCtrl.setToolTip(_translate("root", "<html><head/><body><p>Connect/disconnect selected port.</p></body></html>"))
        self.PB_commPortCtrl.setText(_translate("root", "not connected"))
        self.PB_serialSetup.setToolTip(_translate("root", "<html><head/><body><p>Setup serial communication protocol.</p></body></html>"))
        self.PB_serialSetup.setText(_translate("root", "..."))
        self.PB_refreshCommPortsList.setToolTip(_translate("root", "<html><head/><body><p>Refresh serial communication ports. This will close connection to current port (if exists).</p></body></html>"))
        self.PB_refreshCommPortsList.setText(_translate("root", "..."))
        self.DD_commPortSelector.setToolTip(_translate("root", "<html><head/><body><p>Select serial communication port</p></body></html>"))
        self.DD_commPortSelector.setWhatsThis(_translate("root", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("root", "Data syntax: numbers ( -128 ... +255), HEX (0xd, 0x4B1D), strings (\"!\", \"my string!\"). Separate with \';\'."))
        self.TI_data2.setPlaceholderText(_translate("root", "Channel 2 data"))
        self.TI_data8.setPlaceholderText(_translate("root", "Channel 8 data"))
        self.PB_send2.setText(_translate("root", "SEND"))
        self.PB_send2.setShortcut(_translate("root", "Ctrl+2"))
        self.label_5.setText(_translate("root", "1:"))
        self.PB_send5.setText(_translate("root", "SEND"))
        self.PB_send5.setShortcut(_translate("root", "Ctrl+5"))
        self.label_12.setText(_translate("root", "8:"))
        self.PB_send3.setText(_translate("root", "SEND"))
        self.PB_send3.setShortcut(_translate("root", "Ctrl+3"))
        self.TI_data6.setPlaceholderText(_translate("root", "Channel 6 data"))
        self.label_9.setText(_translate("root", "5:"))
        self.TI_note6.setPlaceholderText(_translate("root", "Channel 6 user note"))
        self.TI_data7.setPlaceholderText(_translate("root", "Channel 7 data"))
        self.PB_send6.setText(_translate("root", "SEND"))
        self.PB_send6.setShortcut(_translate("root", "Ctrl+6"))
        self.TI_note8.setPlaceholderText(_translate("root", "Channel 8 user note"))
        self.TI_note5.setPlaceholderText(_translate("root", "Channel 5 user note"))
        self.TI_note1.setPlaceholderText(_translate("root", "Channel 1 user note"))
        self.PB_send4.setText(_translate("root", "SEND"))
        self.PB_send4.setShortcut(_translate("root", "Ctrl+4"))
        self.TI_data1.setPlaceholderText(_translate("root", "Channel 1 data"))
        self.PB_send7.setText(_translate("root", "SEND"))
        self.PB_send7.setShortcut(_translate("root", "Ctrl+7"))
        self.TI_note2.setPlaceholderText(_translate("root", "Channel 2 user note"))
        self.label_10.setText(_translate("root", "6:"))
        self.TI_data5.setPlaceholderText(_translate("root", "Channel 5 data"))
        self.label_8.setText(_translate("root", "4:"))
        self.TI_data4.setPlaceholderText(_translate("root", "Channel 4 data"))
        self.label_6.setText(_translate("root", "2:"))
        self.TI_note3.setPlaceholderText(_translate("root", "Channel 3 user note"))
        self.TI_note7.setPlaceholderText(_translate("root", "Channel 7 user note"))
        self.TI_note4.setPlaceholderText(_translate("root", "Channel 4 user note"))
        self.PB_send8.setText(_translate("root", "SEND"))
        self.PB_send8.setShortcut(_translate("root", "Ctrl+8"))
        self.label_11.setText(_translate("root", "7:"))
        self.label_7.setText(_translate("root", "3:"))
        self.PB_send1.setText(_translate("root", "SEND"))
        self.PB_send1.setShortcut(_translate("root", "Ctrl+1"))
        self.TI_data3.setPlaceholderText(_translate("root", "Channel 3 data"))
        self.PB_sendSequence2.setToolTip(_translate("root", "<html><head/><body><p>Send/Stop sequence.</p></body></html>"))
        self.PB_sendSequence2.setText(_translate("root", "SEND SEQUENCE"))
        self.PB_sendSequence2.setShortcut(_translate("root", "Ctrl+Shift+2"))
        self.PB_sendSequence3.setToolTip(_translate("root", "<html><head/><body><p>Send/Stop sequence.</p></body></html>"))
        self.PB_sendSequence3.setText(_translate("root", "SEND SEQUENCE"))
        self.PB_sendSequence3.setShortcut(_translate("root", "Ctrl+Shift+3"))
        self.PB_sendSequence1.setToolTip(_translate("root", "<html><head/><body><p>Send/Stop sequence.</p></body></html>"))
        self.PB_sendSequence1.setText(_translate("root", "SEND SEQUENCE"))
        self.PB_sendSequence1.setShortcut(_translate("root", "Ctrl+Shift+1"))
        self.TI_sequence3.setPlaceholderText(_translate("root", "Sequence channel 3 description"))
        self.TI_sequence2.setPlaceholderText(_translate("root", "Sequence channel 2 description"))
        self.TI_sequence1.setPlaceholderText(_translate("root", "Sequence channel 1 description"))
        self.label_13.setText(_translate("root", "Sequence syntax: (<data channel number 1 - 8>, <delay after data send in ms>, <optionally: repeat number> ); (-//-); (-//-); ..."))
        self.PB_clearLog.setToolTip(_translate("root", "<html><head/><body><p>Clear log window (Ctrl+Shift+C)</p></body></html>"))
        self.PB_clearLog.setText(_translate("root", "..."))
        self.PB_clearLog.setShortcut(_translate("root", "Ctrl+Shift+C"))
        self.PB_exportLog.setToolTip(_translate("root", "<html><head/><body><p>Save log window data.</p></body></html>"))
        self.PB_exportLog.setText(_translate("root", "..."))
        self.PB_exportRxTxData.setToolTip(_translate("root", "<html><head/><body><p>Save raw RX/TX data.</p></body></html>"))
        self.PB_exportRxTxData.setText(_translate("root", "..."))
        self.CB_rxToLog.setToolTip(_translate("root", "<html><head/><body><p>Show received data</p></body></html>"))
        self.CB_rxToLog.setText(_translate("root", "RX"))
        self.CB_txToLog.setToolTip(_translate("root", "<html><head/><body><p>Show transmitted data</p></body></html>"))
        self.CB_txToLog.setText(_translate("root", "TX"))
        self.RB_outputRepresentationString.setToolTip(_translate("root", "<html><head/><body><p>Set data representation to string format</p></body></html>"))
        self.RB_outputRepresentationString.setText(_translate("root", "String"))
        self.RB_outputRepresentationIntList.setToolTip(_translate("root", "<html><head/><body><p>Set data representation format to a list of integer numbers</p></body></html>"))
        self.RB_outputRepresentationIntList.setText(_translate("root", "INT list"))
        self.RB_outputRepresentationHexList.setToolTip(_translate("root", "<html><head/><body><p>Set data representation format to a list of hex numbers</p></body></html>"))
        self.RB_outputRepresentationHexList.setText(_translate("root", "HEX list"))
        self.RB_outputRepresentationAsciiList.setToolTip(_translate("root", "<html><head/><body><p>Set data representation format to a list of ASCII characters</p></body></html>"))
        self.RB_outputRepresentationAsciiList.setText(_translate("root", "ASCII list"))
        self.CB_rxNewLine.setToolTip(_translate("root", "<html><head/><body><p>Display each received data on a new line.</p></body></html>"))
        self.CB_rxNewLine.setText(_translate("root", "\\n on RX data"))
        self.SB_rxTimeoutMs.setToolTip(_translate("root", "<html><head/><body><p>Interval after \'\\n\' is inserted once new data is received. </p></body></html>"))
        self.SB_rxTimeoutMs.setSuffix(_translate("root", "ms"))
        self.PB_autoScroll.setToolTip(_translate("root", "<html><head/><body><p>Enable/disable auto scroll</p></body></html>"))
        self.PB_autoScroll.setText(_translate("root", "..."))
        self.TE_log.setHtml(_translate("root", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuFile.setTitle(_translate("root", "File"))
        self.PB_fileMenu_recentlyUsedConfigurations.setTitle(_translate("root", "Recently used configurations"))
        self.menuHelp.setTitle(_translate("root", "Help"))
        self.PB_fileMenu_saveConfiguration.setText(_translate("root", "Save configuration..."))
        self.PB_fileMenu_saveConfiguration.setShortcut(_translate("root", "Ctrl+S"))
        self.PB_fileMenu_loadConfiguration.setText(_translate("root", "Load configuration..."))
        self.PB_fileMenu_loadConfiguration.setShortcut(_translate("root", "Ctrl+O"))
        self.PB_fileMenu_newConfiguration.setText(_translate("root", "New configuration"))
        self.PB_fileMenu_newConfiguration.setShortcut(_translate("root", "Ctrl+N"))
        self.setup_clear_log.setText(_translate("root", "Clear log"))
        self.setup_hex_output.setText(_translate("root", "HEX output"))
        self.setup_hex_output.setToolTip(_translate("root", "HEX output (list)"))
        self.setup_ascii_output.setText(_translate("root", "ASCII output"))
        self.setup_ascii_output.setToolTip(_translate("root", "ASCII output  (list)"))
        self.setup_serial.setText(_translate("root", "Serial setup"))
        self.file_about.setText(_translate("root", "About"))
        self.setup_string_output.setText(_translate("root", "String output"))
        self.PB_helpMenu_about.setText(_translate("root", "About"))
        self.PB_helpMenu_docs.setText(_translate("root", "Docs"))
        self.PB_helpMenu_docs.setShortcut(_translate("root", "F1"))
        self.PB_helpMenu_checkForUpdate.setText(_translate("root", "Check for update"))
        self.actionAsd.setText(_translate("root", "asd"))
        self.PB_helpMenu_openLogFile.setText(_translate("root", "Open log file"))
from gui import icons_rc
