# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName(_fromUtf8("root"))
        root.setWindowModality(QtCore.Qt.WindowModal)
        root.setEnabled(True)
        root.resize(713, 642)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(root.sizePolicy().hasHeightForWidth())
        root.setSizePolicy(sizePolicy)
        root.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        root.setFont(font)
        root.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("damogranlabs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        root.setWindowIcon(icon)
        root.setIconSize(QtCore.QSize(16, 16))
        root.setAnimated(True)
        root.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(root)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setText(_fromUtf8("Port state:"))
        self.label_4.setIndent(-1)
        self.label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.com_port_selector = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_port_selector.sizePolicy().hasHeightForWidth())
        self.com_port_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.com_port_selector.setFont(font)
        self.com_port_selector.setObjectName(_fromUtf8("com_port_selector"))
        self.gridLayout.addWidget(self.com_port_selector, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8("Baud rate:"))
        self.label_3.setIndent(-1)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.baud_rate_selector = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baud_rate_selector.sizePolicy().hasHeightForWidth())
        self.baud_rate_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.baud_rate_selector.setFont(font)
        self.baud_rate_selector.setObjectName(_fromUtf8("baud_rate_selector"))
        self.baud_rate_selector.addItem(_fromUtf8(""))
        self.baud_rate_selector.addItem(_fromUtf8(""))
        self.baud_rate_selector.addItem(_fromUtf8(""))
        self.baud_rate_selector.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.baud_rate_selector, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8("COM port:"))
        self.label_2.setIndent(-1)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.connection_state = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_state.sizePolicy().hasHeightForWidth())
        self.connection_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.connection_state.setFont(font)
        self.connection_state.setText(_fromUtf8("not connected"))
        self.connection_state.setAlignment(QtCore.Qt.AlignCenter)
        self.connection_state.setIndent(-1)
        self.connection_state.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.connection_state.setObjectName(_fromUtf8("connection_state"))
        self.gridLayout.addWidget(self.connection_state, 1, 2, 1, 1)
        self.com_port_refresh = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_port_refresh.sizePolicy().hasHeightForWidth())
        self.com_port_refresh.setSizePolicy(sizePolicy)
        self.com_port_refresh.setMinimumSize(QtCore.QSize(0, 0))
        self.com_port_refresh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.com_port_refresh.setFont(font)
        self.com_port_refresh.setObjectName(_fromUtf8("com_port_refresh"))
        self.gridLayout.addWidget(self.com_port_refresh, 0, 3, 1, 1)
        self.com_port_connect = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_port_connect.sizePolicy().hasHeightForWidth())
        self.com_port_connect.setSizePolicy(sizePolicy)
        self.com_port_connect.setMinimumSize(QtCore.QSize(0, 0))
        self.com_port_connect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.com_port_connect.setFont(font)
        self.com_port_connect.setObjectName(_fromUtf8("com_port_connect"))
        self.gridLayout.addWidget(self.com_port_connect, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 1)
        self.data_4 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_4.setFont(font)
        self.data_4.setObjectName(_fromUtf8("data_4"))
        self.gridLayout_2.addWidget(self.data_4, 4, 1, 1, 1)
        self.data_5 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_5.setFont(font)
        self.data_5.setObjectName(_fromUtf8("data_5"))
        self.gridLayout_2.addWidget(self.data_5, 5, 1, 1, 1)
        self.data_3 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_3.setFont(font)
        self.data_3.setObjectName(_fromUtf8("data_3"))
        self.gridLayout_2.addWidget(self.data_3, 3, 1, 1, 1)
        self.send_8 = QtGui.QPushButton(self.centralwidget)
        self.send_8.setObjectName(_fromUtf8("send_8"))
        self.gridLayout_2.addWidget(self.send_8, 8, 4, 1, 1)
        self.data_2 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_2.setFont(font)
        self.data_2.setObjectName(_fromUtf8("data_2"))
        self.gridLayout_2.addWidget(self.data_2, 2, 1, 1, 1)
        self.data_8 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_8.setFont(font)
        self.data_8.setObjectName(_fromUtf8("data_8"))
        self.gridLayout_2.addWidget(self.data_8, 8, 1, 1, 1)
        self.data_7 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_7.setFont(font)
        self.data_7.setObjectName(_fromUtf8("data_7"))
        self.gridLayout_2.addWidget(self.data_7, 7, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.data_6 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_6.setFont(font)
        self.data_6.setObjectName(_fromUtf8("data_6"))
        self.gridLayout_2.addWidget(self.data_6, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.data_1 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_1.setFont(font)
        self.data_1.setObjectName(_fromUtf8("data_1"))
        self.gridLayout_2.addWidget(self.data_1, 1, 1, 1, 1)
        self.send_1 = QtGui.QPushButton(self.centralwidget)
        self.send_1.setObjectName(_fromUtf8("send_1"))
        self.gridLayout_2.addWidget(self.send_1, 1, 4, 1, 1)
        self.send_2 = QtGui.QPushButton(self.centralwidget)
        self.send_2.setObjectName(_fromUtf8("send_2"))
        self.gridLayout_2.addWidget(self.send_2, 2, 4, 1, 1)
        self.send_3 = QtGui.QPushButton(self.centralwidget)
        self.send_3.setObjectName(_fromUtf8("send_3"))
        self.gridLayout_2.addWidget(self.send_3, 3, 4, 1, 1)
        self.send_5 = QtGui.QPushButton(self.centralwidget)
        self.send_5.setObjectName(_fromUtf8("send_5"))
        self.gridLayout_2.addWidget(self.send_5, 5, 4, 1, 1)
        self.send_4 = QtGui.QPushButton(self.centralwidget)
        self.send_4.setObjectName(_fromUtf8("send_4"))
        self.gridLayout_2.addWidget(self.send_4, 4, 4, 1, 1)
        self.send_6 = QtGui.QPushButton(self.centralwidget)
        self.send_6.setObjectName(_fromUtf8("send_6"))
        self.gridLayout_2.addWidget(self.send_6, 6, 4, 1, 1)
        self.send_7 = QtGui.QPushButton(self.centralwidget)
        self.send_7.setObjectName(_fromUtf8("send_7"))
        self.gridLayout_2.addWidget(self.send_7, 7, 4, 1, 1)
        self.note_1 = QtGui.QLineEdit(self.centralwidget)
        self.note_1.setObjectName(_fromUtf8("note_1"))
        self.gridLayout_2.addWidget(self.note_1, 1, 2, 1, 1)
        self.note_2 = QtGui.QLineEdit(self.centralwidget)
        self.note_2.setObjectName(_fromUtf8("note_2"))
        self.gridLayout_2.addWidget(self.note_2, 2, 2, 1, 1)
        self.note_3 = QtGui.QLineEdit(self.centralwidget)
        self.note_3.setObjectName(_fromUtf8("note_3"))
        self.gridLayout_2.addWidget(self.note_3, 3, 2, 1, 1)
        self.note_4 = QtGui.QLineEdit(self.centralwidget)
        self.note_4.setObjectName(_fromUtf8("note_4"))
        self.gridLayout_2.addWidget(self.note_4, 4, 2, 1, 1)
        self.note_5 = QtGui.QLineEdit(self.centralwidget)
        self.note_5.setObjectName(_fromUtf8("note_5"))
        self.gridLayout_2.addWidget(self.note_5, 5, 2, 1, 1)
        self.note_6 = QtGui.QLineEdit(self.centralwidget)
        self.note_6.setObjectName(_fromUtf8("note_6"))
        self.gridLayout_2.addWidget(self.note_6, 6, 2, 1, 1)
        self.note_7 = QtGui.QLineEdit(self.centralwidget)
        self.note_7.setObjectName(_fromUtf8("note_7"))
        self.gridLayout_2.addWidget(self.note_7, 7, 2, 1, 1)
        self.note_8 = QtGui.QLineEdit(self.centralwidget)
        self.note_8.setObjectName(_fromUtf8("note_8"))
        self.gridLayout_2.addWidget(self.note_8, 8, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.delay_1 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_1.sizePolicy().hasHeightForWidth())
        self.delay_1.setSizePolicy(sizePolicy)
        self.delay_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_1.setFrame(True)
        self.delay_1.setObjectName(_fromUtf8("delay_1"))
        self.gridLayout_2.addWidget(self.delay_1, 1, 3, 1, 1)
        self.delay_2 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_2.sizePolicy().hasHeightForWidth())
        self.delay_2.setSizePolicy(sizePolicy)
        self.delay_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_2.setFrame(True)
        self.delay_2.setObjectName(_fromUtf8("delay_2"))
        self.gridLayout_2.addWidget(self.delay_2, 2, 3, 1, 1)
        self.delay_3 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_3.sizePolicy().hasHeightForWidth())
        self.delay_3.setSizePolicy(sizePolicy)
        self.delay_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_3.setFrame(True)
        self.delay_3.setObjectName(_fromUtf8("delay_3"))
        self.gridLayout_2.addWidget(self.delay_3, 3, 3, 1, 1)
        self.delay_4 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_4.sizePolicy().hasHeightForWidth())
        self.delay_4.setSizePolicy(sizePolicy)
        self.delay_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_4.setFrame(True)
        self.delay_4.setObjectName(_fromUtf8("delay_4"))
        self.gridLayout_2.addWidget(self.delay_4, 4, 3, 1, 1)
        self.delay_5 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_5.sizePolicy().hasHeightForWidth())
        self.delay_5.setSizePolicy(sizePolicy)
        self.delay_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_5.setFrame(True)
        self.delay_5.setObjectName(_fromUtf8("delay_5"))
        self.gridLayout_2.addWidget(self.delay_5, 5, 3, 1, 1)
        self.delay_6 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_6.sizePolicy().hasHeightForWidth())
        self.delay_6.setSizePolicy(sizePolicy)
        self.delay_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_6.setFrame(True)
        self.delay_6.setObjectName(_fromUtf8("delay_6"))
        self.gridLayout_2.addWidget(self.delay_6, 6, 3, 1, 1)
        self.delay_7 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_7.sizePolicy().hasHeightForWidth())
        self.delay_7.setSizePolicy(sizePolicy)
        self.delay_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_7.setFrame(True)
        self.delay_7.setObjectName(_fromUtf8("delay_7"))
        self.gridLayout_2.addWidget(self.delay_7, 7, 3, 1, 1)
        self.delay_8 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_8.sizePolicy().hasHeightForWidth())
        self.delay_8.setSizePolicy(sizePolicy)
        self.delay_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delay_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_8.setFrame(True)
        self.delay_8.setObjectName(_fromUtf8("delay_8"))
        self.gridLayout_2.addWidget(self.delay_8, 8, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.send_sequence_1 = QtGui.QPushButton(self.centralwidget)
        self.send_sequence_1.setObjectName(_fromUtf8("send_sequence_1"))
        self.gridLayout_3.addWidget(self.send_sequence_1, 0, 5, 1, 1)
        self.command_1_1 = QtGui.QComboBox(self.centralwidget)
        self.command_1_1.setEditable(False)
        self.command_1_1.setMaxCount(9)
        self.command_1_1.setObjectName(_fromUtf8("command_1_1"))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.setItemText(0, _fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.command_1_1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_1_1, 0, 0, 1, 1)
        self.command_1_4 = QtGui.QComboBox(self.centralwidget)
        self.command_1_4.setMaxCount(9)
        self.command_1_4.setObjectName(_fromUtf8("command_1_4"))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.setItemText(0, _fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.command_1_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_1_4, 0, 3, 1, 1)
        self.command_1_3 = QtGui.QComboBox(self.centralwidget)
        self.command_1_3.setMaxCount(9)
        self.command_1_3.setObjectName(_fromUtf8("command_1_3"))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.setItemText(0, _fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.command_1_3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_1_3, 0, 2, 1, 1)
        self.command_1_5 = QtGui.QComboBox(self.centralwidget)
        self.command_1_5.setMaxCount(9)
        self.command_1_5.setObjectName(_fromUtf8("command_1_5"))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.setItemText(0, _fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.command_1_5.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_1_5, 0, 4, 1, 1)
        self.command_1_2 = QtGui.QComboBox(self.centralwidget)
        self.command_1_2.setMaxCount(9)
        self.command_1_2.setObjectName(_fromUtf8("command_1_2"))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.setItemText(0, _fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.command_1_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_1_2, 0, 1, 1, 1)
        self.command_2_5 = QtGui.QComboBox(self.centralwidget)
        self.command_2_5.setMaxCount(9)
        self.command_2_5.setObjectName(_fromUtf8("command_2_5"))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.setItemText(0, _fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.command_2_5.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_2_5, 1, 4, 1, 1)
        self.command_2_1 = QtGui.QComboBox(self.centralwidget)
        self.command_2_1.setMaxCount(9)
        self.command_2_1.setObjectName(_fromUtf8("command_2_1"))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.setItemText(0, _fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.command_2_1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_2_1, 1, 0, 1, 1)
        self.command_2_2 = QtGui.QComboBox(self.centralwidget)
        self.command_2_2.setMaxCount(9)
        self.command_2_2.setObjectName(_fromUtf8("command_2_2"))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.setItemText(0, _fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.command_2_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_2_2, 1, 1, 1, 1)
        self.command_2_3 = QtGui.QComboBox(self.centralwidget)
        self.command_2_3.setMaxCount(9)
        self.command_2_3.setObjectName(_fromUtf8("command_2_3"))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.setItemText(0, _fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.command_2_3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_2_3, 1, 2, 1, 1)
        self.command_2_4 = QtGui.QComboBox(self.centralwidget)
        self.command_2_4.setMaxCount(9)
        self.command_2_4.setObjectName(_fromUtf8("command_2_4"))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.setItemText(0, _fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.command_2_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_2_4, 1, 3, 1, 1)
        self.command_3_1 = QtGui.QComboBox(self.centralwidget)
        self.command_3_1.setMaxCount(9)
        self.command_3_1.setObjectName(_fromUtf8("command_3_1"))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.setItemText(0, _fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.command_3_1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_3_1, 2, 0, 1, 1)
        self.command_3_2 = QtGui.QComboBox(self.centralwidget)
        self.command_3_2.setMaxCount(9)
        self.command_3_2.setObjectName(_fromUtf8("command_3_2"))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.setItemText(0, _fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.command_3_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_3_2, 2, 1, 1, 1)
        self.command_3_3 = QtGui.QComboBox(self.centralwidget)
        self.command_3_3.setMaxCount(9)
        self.command_3_3.setObjectName(_fromUtf8("command_3_3"))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.setItemText(0, _fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.command_3_3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_3_3, 2, 2, 1, 1)
        self.command_3_4 = QtGui.QComboBox(self.centralwidget)
        self.command_3_4.setMaxCount(9)
        self.command_3_4.setObjectName(_fromUtf8("command_3_4"))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.setItemText(0, _fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.command_3_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_3_4, 2, 3, 1, 1)
        self.command_3_5 = QtGui.QComboBox(self.centralwidget)
        self.command_3_5.setMaxCount(9)
        self.command_3_5.setObjectName(_fromUtf8("command_3_5"))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.setItemText(0, _fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.command_3_5.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.command_3_5, 2, 4, 1, 1)
        self.send_sequence_2 = QtGui.QPushButton(self.centralwidget)
        self.send_sequence_2.setObjectName(_fromUtf8("send_sequence_2"))
        self.gridLayout_3.addWidget(self.send_sequence_2, 1, 5, 1, 1)
        self.send_sequence_3 = QtGui.QPushButton(self.centralwidget)
        self.send_sequence_3.setObjectName(_fromUtf8("send_sequence_3"))
        self.gridLayout_3.addWidget(self.send_sequence_3, 2, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.data_log = QtGui.QTextEdit(self.centralwidget)
        self.data_log.setUndoRedoEnabled(False)
        self.data_log.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.data_log.setObjectName(_fromUtf8("data_log"))
        self.verticalLayout.addWidget(self.data_log)
        root.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(root)
        self.statusbar.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.statusbar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        root.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(root)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetup = QtGui.QMenu(self.menuBar)
        self.menuSetup.setObjectName(_fromUtf8("menuSetup"))
        root.setMenuBar(self.menuBar)
        self.file_save_configuration = QtGui.QAction(root)
        self.file_save_configuration.setObjectName(_fromUtf8("file_save_configuration"))
        self.file_load_configuration = QtGui.QAction(root)
        self.file_load_configuration.setObjectName(_fromUtf8("file_load_configuration"))
        self.file_new_configuration = QtGui.QAction(root)
        self.file_new_configuration.setObjectName(_fromUtf8("file_new_configuration"))
        self.setup_clear_log = QtGui.QAction(root)
        self.setup_clear_log.setObjectName(_fromUtf8("setup_clear_log"))
        self.setup_hex_output = QtGui.QAction(root)
        self.setup_hex_output.setCheckable(True)
        self.setup_hex_output.setChecked(True)
        self.setup_hex_output.setObjectName(_fromUtf8("setup_hex_output"))
        self.setup_ascii_output = QtGui.QAction(root)
        self.setup_ascii_output.setCheckable(True)
        self.setup_ascii_output.setObjectName(_fromUtf8("setup_ascii_output"))
        self.setup_serial = QtGui.QAction(root)
        self.setup_serial.setObjectName(_fromUtf8("setup_serial"))
        self.file_about = QtGui.QAction(root)
        self.file_about.setObjectName(_fromUtf8("file_about"))
        self.menuFile.addAction(self.file_new_configuration)
        self.menuFile.addAction(self.file_save_configuration)
        self.menuFile.addAction(self.file_load_configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_about)
        self.menuSetup.addAction(self.setup_serial)
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.setup_hex_output)
        self.menuSetup.addAction(self.setup_ascii_output)
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.setup_clear_log)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetup.menuAction())

        self.retranslateUi(root)
        self.command_1_1.setCurrentIndex(0)
        self.command_1_4.setCurrentIndex(0)
        self.command_1_3.setCurrentIndex(0)
        self.command_1_5.setCurrentIndex(0)
        self.command_1_2.setCurrentIndex(0)
        self.command_2_5.setCurrentIndex(0)
        self.command_2_1.setCurrentIndex(0)
        self.command_2_2.setCurrentIndex(0)
        self.command_2_3.setCurrentIndex(0)
        self.command_2_4.setCurrentIndex(0)
        self.command_3_1.setCurrentIndex(0)
        self.command_3_2.setCurrentIndex(0)
        self.command_3_3.setCurrentIndex(0)
        self.command_3_4.setCurrentIndex(0)
        self.command_3_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(root)
        root.setTabOrder(self.com_port_selector, self.baud_rate_selector)
        root.setTabOrder(self.baud_rate_selector, self.com_port_refresh)
        root.setTabOrder(self.com_port_refresh, self.com_port_connect)
        root.setTabOrder(self.com_port_connect, self.data_1)
        root.setTabOrder(self.data_1, self.note_1)
        root.setTabOrder(self.note_1, self.delay_1)
        root.setTabOrder(self.delay_1, self.send_1)
        root.setTabOrder(self.send_1, self.data_2)
        root.setTabOrder(self.data_2, self.note_2)
        root.setTabOrder(self.note_2, self.delay_2)
        root.setTabOrder(self.delay_2, self.send_2)
        root.setTabOrder(self.send_2, self.data_3)
        root.setTabOrder(self.data_3, self.note_3)
        root.setTabOrder(self.note_3, self.delay_3)
        root.setTabOrder(self.delay_3, self.send_3)
        root.setTabOrder(self.send_3, self.data_4)
        root.setTabOrder(self.data_4, self.note_4)
        root.setTabOrder(self.note_4, self.delay_4)
        root.setTabOrder(self.delay_4, self.send_4)
        root.setTabOrder(self.send_4, self.data_5)
        root.setTabOrder(self.data_5, self.note_5)
        root.setTabOrder(self.note_5, self.delay_5)
        root.setTabOrder(self.delay_5, self.send_5)
        root.setTabOrder(self.send_5, self.data_6)
        root.setTabOrder(self.data_6, self.note_6)
        root.setTabOrder(self.note_6, self.delay_6)
        root.setTabOrder(self.delay_6, self.send_6)
        root.setTabOrder(self.send_6, self.data_7)
        root.setTabOrder(self.data_7, self.note_7)
        root.setTabOrder(self.note_7, self.delay_7)
        root.setTabOrder(self.delay_7, self.send_7)
        root.setTabOrder(self.send_7, self.data_8)
        root.setTabOrder(self.data_8, self.note_8)
        root.setTabOrder(self.note_8, self.delay_8)
        root.setTabOrder(self.delay_8, self.send_8)
        root.setTabOrder(self.send_8, self.command_1_1)
        root.setTabOrder(self.command_1_1, self.command_1_2)
        root.setTabOrder(self.command_1_2, self.command_1_3)
        root.setTabOrder(self.command_1_3, self.command_1_4)
        root.setTabOrder(self.command_1_4, self.command_1_5)
        root.setTabOrder(self.command_1_5, self.send_sequence_1)
        root.setTabOrder(self.send_sequence_1, self.command_2_1)
        root.setTabOrder(self.command_2_1, self.command_2_2)
        root.setTabOrder(self.command_2_2, self.command_2_3)
        root.setTabOrder(self.command_2_3, self.command_2_4)
        root.setTabOrder(self.command_2_4, self.command_2_5)
        root.setTabOrder(self.command_2_5, self.send_sequence_2)
        root.setTabOrder(self.send_sequence_2, self.command_3_1)
        root.setTabOrder(self.command_3_1, self.command_3_2)
        root.setTabOrder(self.command_3_2, self.command_3_3)
        root.setTabOrder(self.command_3_3, self.command_3_4)
        root.setTabOrder(self.command_3_4, self.command_3_5)
        root.setTabOrder(self.command_3_5, self.send_sequence_3)
        root.setTabOrder(self.send_sequence_3, self.data_log)

    def retranslateUi(self, root):
        root.setWindowTitle(_translate("root", "Serial tool", None))
        self.baud_rate_selector.setItemText(0, _translate("root", "115200", None))
        self.baud_rate_selector.setItemText(1, _translate("root", "38400", None))
        self.baud_rate_selector.setItemText(2, _translate("root", "19200", None))
        self.baud_rate_selector.setItemText(3, _translate("root", "9600", None))
        self.com_port_refresh.setText(_translate("root", "REFRESH", None))
        self.com_port_connect.setText(_translate("root", "CONNECT", None))
        self.label.setText(_translate("root", "Enter bytes(0 .. 255) or characters (eg. a) and separate them with comma and space: (eg: F, 255, 30, a):", None))
        self.label_10.setText(_translate("root", "6:", None))
        self.label_9.setText(_translate("root", "5:", None))
        self.label_8.setText(_translate("root", "4:", None))
        self.label_11.setText(_translate("root", "7:", None))
        self.label_12.setText(_translate("root", "8:", None))
        self.send_8.setText(_translate("root", "SEND", None))
        self.label_5.setText(_translate("root", "1:", None))
        self.label_6.setText(_translate("root", "2:", None))
        self.label_7.setText(_translate("root", "3:", None))
        self.send_1.setText(_translate("root", "SEND", None))
        self.send_2.setText(_translate("root", "SEND", None))
        self.send_3.setText(_translate("root", "SEND", None))
        self.send_5.setText(_translate("root", "SEND", None))
        self.send_4.setText(_translate("root", "SEND", None))
        self.send_6.setText(_translate("root", "SEND", None))
        self.send_7.setText(_translate("root", "SEND", None))
        self.label_14.setText(_translate("root", "DATA:", None))
        self.label_15.setText(_translate("root", "NOTE:", None))
        self.delay_1.setText(_translate("root", "0", None))
        self.delay_2.setText(_translate("root", "0", None))
        self.delay_3.setText(_translate("root", "0", None))
        self.delay_4.setText(_translate("root", "0", None))
        self.delay_5.setText(_translate("root", "0", None))
        self.delay_6.setText(_translate("root", "0", None))
        self.delay_7.setText(_translate("root", "0", None))
        self.delay_8.setText(_translate("root", "0", None))
        self.label_16.setText(_translate("root", "DELAY [ms]:", None))
        self.label_17.setText(_translate("root", "CH:", None))
        self.send_sequence_1.setText(_translate("root", "SEND SEQUENCE", None))
        self.command_1_1.setItemText(1, _translate("root", "1", None))
        self.command_1_1.setItemText(2, _translate("root", "2", None))
        self.command_1_1.setItemText(3, _translate("root", "3", None))
        self.command_1_1.setItemText(4, _translate("root", "4", None))
        self.command_1_1.setItemText(5, _translate("root", "5", None))
        self.command_1_1.setItemText(6, _translate("root", "6", None))
        self.command_1_1.setItemText(7, _translate("root", "7", None))
        self.command_1_1.setItemText(8, _translate("root", "8", None))
        self.command_1_4.setItemText(1, _translate("root", "1", None))
        self.command_1_4.setItemText(2, _translate("root", "2", None))
        self.command_1_4.setItemText(3, _translate("root", "3", None))
        self.command_1_4.setItemText(4, _translate("root", "4", None))
        self.command_1_4.setItemText(5, _translate("root", "5", None))
        self.command_1_4.setItemText(6, _translate("root", "6", None))
        self.command_1_4.setItemText(7, _translate("root", "7", None))
        self.command_1_4.setItemText(8, _translate("root", "8", None))
        self.command_1_3.setItemText(1, _translate("root", "1", None))
        self.command_1_3.setItemText(2, _translate("root", "2", None))
        self.command_1_3.setItemText(3, _translate("root", "3", None))
        self.command_1_3.setItemText(4, _translate("root", "4", None))
        self.command_1_3.setItemText(5, _translate("root", "5", None))
        self.command_1_3.setItemText(6, _translate("root", "6", None))
        self.command_1_3.setItemText(7, _translate("root", "7", None))
        self.command_1_3.setItemText(8, _translate("root", "8", None))
        self.command_1_5.setItemText(1, _translate("root", "1", None))
        self.command_1_5.setItemText(2, _translate("root", "2", None))
        self.command_1_5.setItemText(3, _translate("root", "3", None))
        self.command_1_5.setItemText(4, _translate("root", "4", None))
        self.command_1_5.setItemText(5, _translate("root", "5", None))
        self.command_1_5.setItemText(6, _translate("root", "6", None))
        self.command_1_5.setItemText(7, _translate("root", "7", None))
        self.command_1_5.setItemText(8, _translate("root", "8", None))
        self.command_1_2.setItemText(1, _translate("root", "1", None))
        self.command_1_2.setItemText(2, _translate("root", "2", None))
        self.command_1_2.setItemText(3, _translate("root", "3", None))
        self.command_1_2.setItemText(4, _translate("root", "4", None))
        self.command_1_2.setItemText(5, _translate("root", "5", None))
        self.command_1_2.setItemText(6, _translate("root", "6", None))
        self.command_1_2.setItemText(7, _translate("root", "7", None))
        self.command_1_2.setItemText(8, _translate("root", "8", None))
        self.command_2_5.setItemText(1, _translate("root", "1", None))
        self.command_2_5.setItemText(2, _translate("root", "2", None))
        self.command_2_5.setItemText(3, _translate("root", "3", None))
        self.command_2_5.setItemText(4, _translate("root", "4", None))
        self.command_2_5.setItemText(5, _translate("root", "5", None))
        self.command_2_5.setItemText(6, _translate("root", "6", None))
        self.command_2_5.setItemText(7, _translate("root", "7", None))
        self.command_2_5.setItemText(8, _translate("root", "8", None))
        self.command_2_1.setItemText(1, _translate("root", "1", None))
        self.command_2_1.setItemText(2, _translate("root", "2", None))
        self.command_2_1.setItemText(3, _translate("root", "3", None))
        self.command_2_1.setItemText(4, _translate("root", "4", None))
        self.command_2_1.setItemText(5, _translate("root", "5", None))
        self.command_2_1.setItemText(6, _translate("root", "6", None))
        self.command_2_1.setItemText(7, _translate("root", "7", None))
        self.command_2_1.setItemText(8, _translate("root", "8", None))
        self.command_2_2.setItemText(1, _translate("root", "1", None))
        self.command_2_2.setItemText(2, _translate("root", "2", None))
        self.command_2_2.setItemText(3, _translate("root", "3", None))
        self.command_2_2.setItemText(4, _translate("root", "4", None))
        self.command_2_2.setItemText(5, _translate("root", "5", None))
        self.command_2_2.setItemText(6, _translate("root", "6", None))
        self.command_2_2.setItemText(7, _translate("root", "7", None))
        self.command_2_2.setItemText(8, _translate("root", "8", None))
        self.command_2_3.setItemText(1, _translate("root", "1", None))
        self.command_2_3.setItemText(2, _translate("root", "2", None))
        self.command_2_3.setItemText(3, _translate("root", "3", None))
        self.command_2_3.setItemText(4, _translate("root", "4", None))
        self.command_2_3.setItemText(5, _translate("root", "5", None))
        self.command_2_3.setItemText(6, _translate("root", "6", None))
        self.command_2_3.setItemText(7, _translate("root", "7", None))
        self.command_2_3.setItemText(8, _translate("root", "8", None))
        self.command_2_4.setItemText(1, _translate("root", "1", None))
        self.command_2_4.setItemText(2, _translate("root", "2", None))
        self.command_2_4.setItemText(3, _translate("root", "3", None))
        self.command_2_4.setItemText(4, _translate("root", "4", None))
        self.command_2_4.setItemText(5, _translate("root", "5", None))
        self.command_2_4.setItemText(6, _translate("root", "6", None))
        self.command_2_4.setItemText(7, _translate("root", "7", None))
        self.command_2_4.setItemText(8, _translate("root", "8", None))
        self.command_3_1.setItemText(1, _translate("root", "1", None))
        self.command_3_1.setItemText(2, _translate("root", "2", None))
        self.command_3_1.setItemText(3, _translate("root", "3", None))
        self.command_3_1.setItemText(4, _translate("root", "4", None))
        self.command_3_1.setItemText(5, _translate("root", "5", None))
        self.command_3_1.setItemText(6, _translate("root", "6", None))
        self.command_3_1.setItemText(7, _translate("root", "7", None))
        self.command_3_1.setItemText(8, _translate("root", "8", None))
        self.command_3_2.setItemText(1, _translate("root", "1", None))
        self.command_3_2.setItemText(2, _translate("root", "2", None))
        self.command_3_2.setItemText(3, _translate("root", "3", None))
        self.command_3_2.setItemText(4, _translate("root", "4", None))
        self.command_3_2.setItemText(5, _translate("root", "5", None))
        self.command_3_2.setItemText(6, _translate("root", "6", None))
        self.command_3_2.setItemText(7, _translate("root", "7", None))
        self.command_3_2.setItemText(8, _translate("root", "8", None))
        self.command_3_3.setItemText(1, _translate("root", "1", None))
        self.command_3_3.setItemText(2, _translate("root", "2", None))
        self.command_3_3.setItemText(3, _translate("root", "3", None))
        self.command_3_3.setItemText(4, _translate("root", "4", None))
        self.command_3_3.setItemText(5, _translate("root", "5", None))
        self.command_3_3.setItemText(6, _translate("root", "6", None))
        self.command_3_3.setItemText(7, _translate("root", "7", None))
        self.command_3_3.setItemText(8, _translate("root", "8", None))
        self.command_3_4.setItemText(1, _translate("root", "1", None))
        self.command_3_4.setItemText(2, _translate("root", "2", None))
        self.command_3_4.setItemText(3, _translate("root", "3", None))
        self.command_3_4.setItemText(4, _translate("root", "4", None))
        self.command_3_4.setItemText(5, _translate("root", "5", None))
        self.command_3_4.setItemText(6, _translate("root", "6", None))
        self.command_3_4.setItemText(7, _translate("root", "7", None))
        self.command_3_4.setItemText(8, _translate("root", "8", None))
        self.command_3_5.setItemText(1, _translate("root", "1", None))
        self.command_3_5.setItemText(2, _translate("root", "2", None))
        self.command_3_5.setItemText(3, _translate("root", "3", None))
        self.command_3_5.setItemText(4, _translate("root", "4", None))
        self.command_3_5.setItemText(5, _translate("root", "5", None))
        self.command_3_5.setItemText(6, _translate("root", "6", None))
        self.command_3_5.setItemText(7, _translate("root", "7", None))
        self.command_3_5.setItemText(8, _translate("root", "8", None))
        self.send_sequence_2.setText(_translate("root", "SEND SEQUENCE", None))
        self.send_sequence_3.setText(_translate("root", "SEND SEQUENCE", None))
        self.menuFile.setTitle(_translate("root", "File", None))
        self.menuSetup.setTitle(_translate("root", "Setup", None))
        self.file_save_configuration.setText(_translate("root", "Save configuration", None))
        self.file_load_configuration.setText(_translate("root", "Load configuration", None))
        self.file_new_configuration.setText(_translate("root", "New configuration", None))
        self.setup_clear_log.setText(_translate("root", "Clear log", None))
        self.setup_hex_output.setText(_translate("root", "HEX output", None))
        self.setup_ascii_output.setText(_translate("root", "ASCII output", None))
        self.setup_serial.setText(_translate("root", "Serial setup", None))
        self.file_about.setText(_translate("root", "About", None))

