# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_setup_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SerialSetupDialog(object):
    def setupUi(self, SerialSetupDialog):
        SerialSetupDialog.setObjectName(_fromUtf8("SerialSetupDialog"))
        SerialSetupDialog.resize(453, 133)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SerialSetupDialog.sizePolicy().hasHeightForWidth())
        SerialSetupDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("damogranlabs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SerialSetupDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(SerialSetupDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bytesize = QtGui.QVBoxLayout()
        self.bytesize.setObjectName(_fromUtf8("bytesize"))
        self.label = QtGui.QLabel(SerialSetupDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.bytesize.addWidget(self.label)
        self.bytesize_eightbits = QtGui.QRadioButton(SerialSetupDialog)
        self.bytesize_eightbits.setChecked(True)
        self.bytesize_eightbits.setObjectName(_fromUtf8("bytesize_eightbits"))
        self.bytesize_group = QtGui.QButtonGroup(SerialSetupDialog)
        self.bytesize_group.setObjectName(_fromUtf8("bytesize_group"))
        self.bytesize_group.addButton(self.bytesize_eightbits)
        self.bytesize.addWidget(self.bytesize_eightbits)
        self.bytesize_sevenbits = QtGui.QRadioButton(SerialSetupDialog)
        self.bytesize_sevenbits.setObjectName(_fromUtf8("bytesize_sevenbits"))
        self.bytesize_group.addButton(self.bytesize_sevenbits)
        self.bytesize.addWidget(self.bytesize_sevenbits)
        self.bytesize_sixbits = QtGui.QRadioButton(SerialSetupDialog)
        self.bytesize_sixbits.setObjectName(_fromUtf8("bytesize_sixbits"))
        self.bytesize_group.addButton(self.bytesize_sixbits)
        self.bytesize.addWidget(self.bytesize_sixbits)
        self.bytesize_fivebits = QtGui.QRadioButton(SerialSetupDialog)
        self.bytesize_fivebits.setObjectName(_fromUtf8("bytesize_fivebits"))
        self.bytesize_group.addButton(self.bytesize_fivebits)
        self.bytesize.addWidget(self.bytesize_fivebits)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.bytesize.addItem(spacerItem)
        self.gridLayout.addLayout(self.bytesize, 0, 2, 1, 1)
        self.parity = QtGui.QVBoxLayout()
        self.parity.setObjectName(_fromUtf8("parity"))
        self.label_2 = QtGui.QLabel(SerialSetupDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.parity.addWidget(self.label_2)
        self.parity_none = QtGui.QRadioButton(SerialSetupDialog)
        self.parity_none.setChecked(True)
        self.parity_none.setObjectName(_fromUtf8("parity_none"))
        self.parity_group = QtGui.QButtonGroup(SerialSetupDialog)
        self.parity_group.setObjectName(_fromUtf8("parity_group"))
        self.parity_group.addButton(self.parity_none)
        self.parity.addWidget(self.parity_none)
        self.parity_even = QtGui.QRadioButton(SerialSetupDialog)
        self.parity_even.setObjectName(_fromUtf8("parity_even"))
        self.parity_group.addButton(self.parity_even)
        self.parity.addWidget(self.parity_even)
        self.parity_odd = QtGui.QRadioButton(SerialSetupDialog)
        self.parity_odd.setObjectName(_fromUtf8("parity_odd"))
        self.parity_group.addButton(self.parity_odd)
        self.parity.addWidget(self.parity_odd)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.parity.addItem(spacerItem1)
        self.gridLayout.addLayout(self.parity, 0, 4, 1, 1)
        self.stop_bits = QtGui.QVBoxLayout()
        self.stop_bits.setObjectName(_fromUtf8("stop_bits"))
        self.label_3 = QtGui.QLabel(SerialSetupDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.stop_bits.addWidget(self.label_3)
        self.stopbits_one = QtGui.QRadioButton(SerialSetupDialog)
        self.stopbits_one.setChecked(True)
        self.stopbits_one.setObjectName(_fromUtf8("stopbits_one"))
        self.stopbits_group = QtGui.QButtonGroup(SerialSetupDialog)
        self.stopbits_group.setObjectName(_fromUtf8("stopbits_group"))
        self.stopbits_group.addButton(self.stopbits_one)
        self.stop_bits.addWidget(self.stopbits_one)
        self.stopbits_two = QtGui.QRadioButton(SerialSetupDialog)
        self.stopbits_two.setObjectName(_fromUtf8("stopbits_two"))
        self.stopbits_group.addButton(self.stopbits_two)
        self.stop_bits.addWidget(self.stopbits_two)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.stop_bits.addItem(spacerItem2)
        self.confirm = QtGui.QPushButton(SerialSetupDialog)
        self.confirm.setObjectName(_fromUtf8("confirm"))
        self.stop_bits.addWidget(self.confirm)
        self.gridLayout.addLayout(self.stop_bits, 0, 6, 1, 1)
        self.flow_control = QtGui.QVBoxLayout()
        self.flow_control.setObjectName(_fromUtf8("flow_control"))
        self.label_4 = QtGui.QLabel(SerialSetupDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.flow_control.addWidget(self.label_4)
        self.flow_xon_xoff = QtGui.QCheckBox(SerialSetupDialog)
        self.flow_xon_xoff.setObjectName(_fromUtf8("flow_xon_xoff"))
        self.flow_control.addWidget(self.flow_xon_xoff)
        self.line_2 = QtGui.QFrame(SerialSetupDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.flow_control.addWidget(self.line_2)
        self.label_5 = QtGui.QLabel(SerialSetupDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.flow_control.addWidget(self.label_5)
        self.flow_rts_cts = QtGui.QCheckBox(SerialSetupDialog)
        self.flow_rts_cts.setObjectName(_fromUtf8("flow_rts_cts"))
        self.flow_control.addWidget(self.flow_rts_cts)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.flow_control.addItem(spacerItem3)
        self.gridLayout.addLayout(self.flow_control, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(SerialSetupDialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.line_4 = QtGui.QFrame(SerialSetupDialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 0, 5, 1, 1)
        self.line = QtGui.QFrame(SerialSetupDialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(SerialSetupDialog)
        QtCore.QMetaObject.connectSlotsByName(SerialSetupDialog)

    def retranslateUi(self, SerialSetupDialog):
        SerialSetupDialog.setWindowTitle(_translate("SerialSetupDialog", "Serial Setup Dialog", None))
        self.label.setText(_translate("SerialSetupDialog", "Byte size:", None))
        self.bytesize_eightbits.setText(_translate("SerialSetupDialog", "EIGHTBITS", None))
        self.bytesize_sevenbits.setText(_translate("SerialSetupDialog", "SEVENBITS", None))
        self.bytesize_sixbits.setText(_translate("SerialSetupDialog", "SIXBITS", None))
        self.bytesize_fivebits.setText(_translate("SerialSetupDialog", "FIVEBITS", None))
        self.label_2.setText(_translate("SerialSetupDialog", "Parity:", None))
        self.parity_none.setText(_translate("SerialSetupDialog", "PARITY_NONE", None))
        self.parity_even.setText(_translate("SerialSetupDialog", "PARITY_EVEN", None))
        self.parity_odd.setText(_translate("SerialSetupDialog", "PARITY_ODD", None))
        self.label_3.setText(_translate("SerialSetupDialog", "Stop bits:", None))
        self.stopbits_one.setText(_translate("SerialSetupDialog", "STOPBITS_ONE", None))
        self.stopbits_two.setText(_translate("SerialSetupDialog", "STOPBITS_TWO", None))
        self.confirm.setText(_translate("SerialSetupDialog", "OK", None))
        self.label_4.setText(_translate("SerialSetupDialog", "Software flow control:", None))
        self.flow_xon_xoff.setText(_translate("SerialSetupDialog", "XON/XOFF", None))
        self.label_5.setText(_translate("SerialSetupDialog", "Hardware flow control:", None))
        self.flow_rts_cts.setText(_translate("SerialSetupDialog", "RTS/CTS", None))

