RED = "#d45353"
GREEN = "#9dff96"
ORANGE = "#f5881b"

DAMOGRANLABS_BLUE = "#4f7fd7"
DAMOGRANLABS_GRAY = "#646464"

COMM_PORT_CONNECTED = GREEN
COMM_PORT_NOT_CONNECTED = RED
SEQ_ACTIVE = ORANGE

INPUT_NONE = "None"  # qt style
INPUT_VALID = GREEN
INPUT_ERROR = RED

LOG_NORMAL = "#000000"
LOG_WARNING = "#ff8000"  # orange
LOG_ERROR = "#ff0000"
LOG_GRAY = DAMOGRANLABS_GRAY

LOG_RX_DATA = DAMOGRANLABS_GRAY
LOG_TX_DATA = DAMOGRANLABS_BLUE
