# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/serialSetupDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialSetupDialog(object):
    def setupUi(self, SerialSetupDialog):
        SerialSetupDialog.setObjectName("SerialSetupDialog")
        SerialSetupDialog.resize(386, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SerialSetupDialog.sizePolicy().hasHeightForWidth())
        SerialSetupDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/SerialTool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SerialSetupDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SerialSetupDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bytesize = QtWidgets.QVBoxLayout()
        self.bytesize.setObjectName("bytesize")
        self.label = QtWidgets.QLabel(SerialSetupDialog)
        self.label.setObjectName("label")
        self.bytesize.addWidget(self.label)
        self.RB_dataSize_eight = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_dataSize_eight.setChecked(True)
        self.RB_dataSize_eight.setObjectName("RB_dataSize_eight")
        self.RB_dataSizeGroup = QtWidgets.QButtonGroup(SerialSetupDialog)
        self.RB_dataSizeGroup.setObjectName("RB_dataSizeGroup")
        self.RB_dataSizeGroup.addButton(self.RB_dataSize_eight)
        self.bytesize.addWidget(self.RB_dataSize_eight)
        self.RB_dataSize_seven = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_dataSize_seven.setObjectName("RB_dataSize_seven")
        self.RB_dataSizeGroup.addButton(self.RB_dataSize_seven)
        self.bytesize.addWidget(self.RB_dataSize_seven)
        self.RB_dataSize_six = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_dataSize_six.setObjectName("RB_dataSize_six")
        self.RB_dataSizeGroup.addButton(self.RB_dataSize_six)
        self.bytesize.addWidget(self.RB_dataSize_six)
        self.RB_dataSize_five = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_dataSize_five.setObjectName("RB_dataSize_five")
        self.RB_dataSizeGroup.addButton(self.RB_dataSize_five)
        self.bytesize.addWidget(self.RB_dataSize_five)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.bytesize.addItem(spacerItem)
        self.gridLayout.addLayout(self.bytesize, 0, 2, 1, 1)
        self.parity = QtWidgets.QVBoxLayout()
        self.parity.setObjectName("parity")
        self.label_2 = QtWidgets.QLabel(SerialSetupDialog)
        self.label_2.setObjectName("label_2")
        self.parity.addWidget(self.label_2)
        self.RB_parity_none = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_parity_none.setChecked(True)
        self.RB_parity_none.setObjectName("RB_parity_none")
        self.RB_parityGroup = QtWidgets.QButtonGroup(SerialSetupDialog)
        self.RB_parityGroup.setObjectName("RB_parityGroup")
        self.RB_parityGroup.addButton(self.RB_parity_none)
        self.parity.addWidget(self.RB_parity_none)
        self.RB_parity_even = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_parity_even.setObjectName("RB_parity_even")
        self.RB_parityGroup.addButton(self.RB_parity_even)
        self.parity.addWidget(self.RB_parity_even)
        self.RB_parity_odd = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_parity_odd.setObjectName("RB_parity_odd")
        self.RB_parityGroup.addButton(self.RB_parity_odd)
        self.parity.addWidget(self.RB_parity_odd)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.parity.addItem(spacerItem1)
        self.gridLayout.addLayout(self.parity, 0, 4, 1, 1)
        self.stop_bits = QtWidgets.QVBoxLayout()
        self.stop_bits.setObjectName("stop_bits")
        self.label_3 = QtWidgets.QLabel(SerialSetupDialog)
        self.label_3.setObjectName("label_3")
        self.stop_bits.addWidget(self.label_3)
        self.RB_stopBits_one = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_stopBits_one.setChecked(True)
        self.RB_stopBits_one.setObjectName("RB_stopBits_one")
        self.RB_stopBitsGroup = QtWidgets.QButtonGroup(SerialSetupDialog)
        self.RB_stopBitsGroup.setObjectName("RB_stopBitsGroup")
        self.RB_stopBitsGroup.addButton(self.RB_stopBits_one)
        self.stop_bits.addWidget(self.RB_stopBits_one)
        self.RB_stopBits_two = QtWidgets.QRadioButton(SerialSetupDialog)
        self.RB_stopBits_two.setObjectName("RB_stopBits_two")
        self.RB_stopBitsGroup.addButton(self.RB_stopBits_two)
        self.stop_bits.addWidget(self.RB_stopBits_two)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stop_bits.addItem(spacerItem2)
        self.gridLayout.addLayout(self.stop_bits, 0, 6, 1, 1)
        self.flow_control = QtWidgets.QVBoxLayout()
        self.flow_control.setObjectName("flow_control")
        self.label_4 = QtWidgets.QLabel(SerialSetupDialog)
        self.label_4.setObjectName("label_4")
        self.flow_control.addWidget(self.label_4)
        self.CB_swFlowCtrl = QtWidgets.QCheckBox(SerialSetupDialog)
        self.CB_swFlowCtrl.setObjectName("CB_swFlowCtrl")
        self.flow_control.addWidget(self.CB_swFlowCtrl)
        self.line_2 = QtWidgets.QFrame(SerialSetupDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.flow_control.addWidget(self.line_2)
        self.label_5 = QtWidgets.QLabel(SerialSetupDialog)
        self.label_5.setObjectName("label_5")
        self.flow_control.addWidget(self.label_5)
        self.CB_hwFlowCtrl = QtWidgets.QCheckBox(SerialSetupDialog)
        self.CB_hwFlowCtrl.setObjectName("CB_hwFlowCtrl")
        self.flow_control.addWidget(self.CB_hwFlowCtrl)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.flow_control.addItem(spacerItem3)
        self.gridLayout.addLayout(self.flow_control, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(SerialSetupDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(SerialSetupDialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 5, 1, 1)
        self.line = QtWidgets.QFrame(SerialSetupDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.PB_OK = QtWidgets.QPushButton(SerialSetupDialog)
        self.PB_OK.setObjectName("PB_OK")
        self.horizontalLayout.addWidget(self.PB_OK)
        self.PB_cancel = QtWidgets.QPushButton(SerialSetupDialog)
        self.PB_cancel.setObjectName("PB_cancel")
        self.horizontalLayout.addWidget(self.PB_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SerialSetupDialog)
        QtCore.QMetaObject.connectSlotsByName(SerialSetupDialog)

    def retranslateUi(self, SerialSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        SerialSetupDialog.setWindowTitle(_translate("SerialSetupDialog", "Serial Setup Dialog"))
        self.label.setText(_translate("SerialSetupDialog", "Data size:"))
        self.RB_dataSize_eight.setText(_translate("SerialSetupDialog", "8"))
        self.RB_dataSize_seven.setText(_translate("SerialSetupDialog", "7"))
        self.RB_dataSize_six.setText(_translate("SerialSetupDialog", "6"))
        self.RB_dataSize_five.setText(_translate("SerialSetupDialog", "5"))
        self.label_2.setText(_translate("SerialSetupDialog", "Parity:"))
        self.RB_parity_none.setText(_translate("SerialSetupDialog", "NONE"))
        self.RB_parity_even.setText(_translate("SerialSetupDialog", "EVEN"))
        self.RB_parity_odd.setText(_translate("SerialSetupDialog", "ODD"))
        self.label_3.setText(_translate("SerialSetupDialog", "Stop bits:"))
        self.RB_stopBits_one.setText(_translate("SerialSetupDialog", "1"))
        self.RB_stopBits_two.setText(_translate("SerialSetupDialog", "2"))
        self.label_4.setText(_translate("SerialSetupDialog", "Software flow control:"))
        self.CB_swFlowCtrl.setText(_translate("SerialSetupDialog", "XON/XOFF"))
        self.label_5.setText(_translate("SerialSetupDialog", "Hardware flow control:"))
        self.CB_hwFlowCtrl.setText(_translate("SerialSetupDialog", "RTS/CTS"))
        self.PB_OK.setText(_translate("SerialSetupDialog", "OK"))
        self.PB_cancel.setText(_translate("SerialSetupDialog", "Cancel"))
from gui import icons_rc
